### ISSUE TITLE
Does not restore mode bits of checked out files

### ISSUE THREAD

**Issue by Finii** [Bhacaz/checkout-files#18]
I want to check out a json file and a script that processes it.

The mode of the script is 775 (`rwxrwxr-x`).
Using `actions/checkout` this is of course also restored.

Not with the action. The checked out script file is non-executable. Of course I can set it with `chmod u+x` and use it in the job, but maybe this action can restore the mode bits?

Thank you for this action, even as it is it saves me a lot of CI time :+1:

**Comment by Bhacaz** [comment]
This action is base on the [Rest API ](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content) to simply download the files trough the Rest API, it doesn't keep the permission  since the file is created by nodejs.

I don't have a simple solution for this, maybe [Git trees](https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28#create-a-tree) could help.

cc @mhung-lingraphica

**Comment by Finii** [comment]
Thanks for the reply.

Had a look at the Git tree API and it seems it provides the information:

![image](https://user-images.githubusercontent.com/16012374/216782001-5f2e357a-01b4-4e72-ae7f-699536e66c70.png)

I'm not sure it is worth the effort, though. In my use-case (I fetch some scripts I want to execute in the workflow) one can just `chmod u+x *`. But maybe worth mentioning that the mode is not restored on your main page.

Very nice action!
